# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2066132c2e7686f7698b657c852d7caedeb6844fb2b29b0218b5cf84d7971c04bebb91ce685b88b632f0cb6f232944eeea24aa3d8c4aa6c5a2ffc696beffb9b

test:
  secret_key_base: 33e51ac49a3e440057199deb89b28678179075402cbc3bcf83a6a106c65fec0f8d5198eeb47062b8421fea851f4dde44af0d5a2bce9534ecdae638608067b145

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
